
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :tests do
    cocoapods(repo_update: true)
    run_tests(scheme: "TOFileKitTests")
  end
end
